### PR TITLE
fix!: update TypeORM to 0.3.7

### LINKED ISSUE #133: Update TypeORM version
nest/typeorm released version 9.0.0 which uses `typeorm v0.3.x`, previously it was using an outdated `v0.2.x`. We have to use the latest stable version of all libraries and frameworks, so we will have to update our nest/typeorm and TypeORM versions.

 I think there were some changes in the TypeORM API. We may have to be careful when we make the switch.

### PR DESCRIPTION
**Pull request by tmorris42**
-Rework Custom Repositories

Fix #133

BREAKING CHANGES:
- TypeORM v0.3 and NestJS/typeorm v9 introduced breaking changes to their API, notably in the `find*` functions and the depreciation of `EntityRepository`
- Uses new `find*` functions
- Replaces PaginatedRepository

### CODE REVIEW

File: backend/src/common/paginate.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+export async function paginate<
+  U extends FindAndCountable,
+  T extends Identifiable,
+>(
+  repository: U,
+  query: FindOptionsWhere<T>,
+  orderOptions: FindOptionsOrder<T>,
+  pageOptions: PageOptionsDto,
+): Promise<PageDto<T>> {
```
Comment (fyusuf-a) [inline backend/src/common/paginate.ts:20]:
```suggestion
export async function paginate<
  Repository extends FindAndCountable<Entity>,
  Entity extends Identifiable,
>(
  repository: Repository,
  query: FindOptionsWhere<Entity>,
  orderOptions: FindOptionsOrder<Entity>,
  pageOptions: PageOptionsDto,
): Promise<PageDto<Entity>> {
```

File: dtos/messages/query-message.dto.ts [hunk 2]
```diff
@@ -1,18 +1,16 @@
...
   })
   @IsOptional()
-  @IsNumberString()
   channel?: string;
 
   @ApiPropertyOptional({
     description: 'Sender Id',
   })
   @IsOptional()
-  @IsNumberString()
```
Comment (fyusuf-a) [inline dtos/messages/query-message.dto.ts:16]: I am not sure of the reason of this change. It is information for 'class-validator'.

File: dtos/memberships/query-membership.dto.ts [hunk 3]
```diff
@@ -15,14 +15,14 @@ export class QueryMembershipDto {
   })
   @IsOptional()
   @IsNumberString()
```
Comment (fyusuf-a) [inline dtos/memberships/query-membership.dto.ts:17]:
```suggestion
```

File: dtos/messages/query-message.dto.ts [hunk 4]
```diff
@@ -1,18 +1,16 @@
...
   sender?: string;
```
Comment (fyusuf-a) [inline dtos/messages/query-message.dto.ts:15]:
```suggestion
  senderId?: number;
```

File: dtos/messages/query-message.dto.ts [hunk 5]
```diff
@@ -1,18 +1,16 @@
...
-import { IsNumberString, IsOptional } from 'class-validator';
+import { IsOptional } from 'class-validator';
 
 export class QueryMessageDto {
   @ApiPropertyOptional({
     description: 'Channel Id',
   })
   @IsOptional()
-  @IsNumberString()
   channel?: string;
```
Comment (fyusuf-a) [inline dtos/messages/query-message.dto.ts:9]:
```suggestion
  channelId?: number;
```

File: dtos/blocks/query-block.dto.ts [hunk 6]
```diff
@@ -8,14 +8,14 @@ export class QueryBlockDto {
   })
   @IsOptional()
   @IsNumberString()
```
Comment (fyusuf-a) [inline dtos/blocks/query-block.dto.ts:10]:
```suggestion
```

File: dtos/blocks/query-block.dto.ts [hunk 7]
```diff
@@ -8,14 +8,14 @@ export class QueryBlockDto {
...
-  sourceId?: string;
+  sourceId?: number;
 
   @ApiPropertyOptional({
     description: 'Target User Id',
   })
   @IsOptional()
   @IsNumberString()
```
Comment (fyusuf-a) [inline dtos/blocks/query-block.dto.ts:17]:
```suggestion
```

File: backend/src/messages/messages.service.spec.ts [hunk 8]
```diff
@@ -89,10 +89,13 @@ describe('MessagesService', () => {
...
   describe('findAll()', () => {
     it('should return an array of messages', async () => {
+      jest
+        .spyOn(repository, 'findAndCount')
+        .mockReturnValue(Promise.resolve([[new Message()], 1]));
       const messages = await service.findAll();
       expect(messages).toBeInstanceOf(PageDto);
       if (messages.data.length !== 0)
-        expect(messages.data[0]).toBeInstanceOf(MockMessageEntity);
+        expect(messages.data[0]).toBeInstanceOf(Message);
```
Comment (fyusuf-a) [inline backend/src/messages/messages.service.spec.ts:98]:
```suggestion
        expect(messages.data[0]).toBeInstanceOf(MockMessageEntity);
```

File: backend/src/messages/messages.service.spec.ts [hunk 9]
```diff
@@ -2,46 +2,46 @@ import { Test, TestingModule } from '@nestjs/testing';
...
+  let repository: Repository<Message>;
 
   beforeEach(async () => {
     const module: TestingModule = await Test.createTestingModule({
       providers: [
         MessagesService,
         {
-          provide: getRepositoryToken(MessageRepository),
+          provide: getRepositoryToken(Message),
           useValue: new MockRepository<MockMessageEntity>(
```
Comment (fyusuf-a) [inline backend/src/messages/messages.service.spec.ts:27]:
```suggestion
          useValue: new MockRepository<Message>(
```
See line 98.

File: backend/src/channels/channels.service.spec.ts [hunk 10]
```diff
@@ -49,8 +54,13 @@ describe('ChannelsService', () => {
...
   describe('when finding all Channels', () => {
     it('should return array of Channel', async () => {
+      jest
+        .spyOn(repository, 'findAndCount')
+        .mockReturnValue(Promise.resolve([[new Channel()], 1]));
       const ret = await service.findAll();
-      expect(ret.data.length).toBe(2);
+      expect(ret).toBeInstanceOf(PageDto);
+      expect(ret.data.length).toBe(1);
+      expect(ret.data[0]).toBeInstanceOf(Channel);
```
Comment (fyusuf-a) [inline backend/src/channels/channels.service.spec.ts:63]:
```suggestion
      const ret = await service.findAll();
      expect(ret.data.length).toBe(2);
      expect(ret).toBeInstanceOf(PageDto);
      expect(ret.data[0]).toBeInstanceOf(Channel);
```
This would work with the acceptance of my suggestion on `repository.mock.ts`.

File: backend/src/common/mocks/repository.mock.ts [hunk 11]
```diff
@@ -34,8 +34,20 @@ export class MockRepository<T extends Identifiable> {
...
+    return this.#entities[query.id];
+  });
   find = jest.fn((): T[] => this.#entities);
+  findAndCount = jest.fn((): [T[], number] => [
+    [...this.#entities],
+    this.#entities.length,
+  ]);
+  findBy = jest.fn((): T[] => this.#entities);
   findAll = jest.fn((): T[] => this.#entities);
+  findAllBy = jest.fn((): T[] => this.#entities);
```
Comment (fyusuf-a) [inline backend/src/common/mocks/repository.mock.ts:50]:
```suggestion
  find = jest.fn((): T[] => this.#entities.filter((x) => x !== undefined));
  findAndCount = jest.fn((): [T[], number] => {
    const returnEntities = this.find();
    return [returnEntities, returnEntities.length];
  });
  findBy = this.find;
  findAll = this.find;
  findAllBy = this.find;
```
Otherwise, there is an `undefined` element at index 0.

Comment (fyusuf-a) [reply backend/src/common/mocks/repository.mock.ts:50]: I would also remove from this file `findAllPaginated`.

File: backend/src/messages/messages.service.spec.ts [hunk 12]
```diff
@@ -89,10 +89,13 @@ describe('MessagesService', () => {
 
   describe('findAll()', () => {
     it('should return an array of messages', async () => {
+      jest
+        .spyOn(repository, 'findAndCount')
+        .mockReturnValue(Promise.resolve([[new Message()], 1]));
```
Comment (fyusuf-a) [inline backend/src/messages/messages.service.spec.ts:94]:
```suggestion
```
See the change to `MockRepository`.

File: backend/src/messages/messages.service.spec.ts (hunk 8 above)
Comment (fyusuf-a) [inline backend/src/messages/messages.service.spec.ts:98]:
```suggestion
        expect(messages.data[0]).toBeInstanceOf(MockMessageEntity);
```

File: backend/src/users/users.service.spec.ts [hunk 13]
```diff
@@ -33,12 +34,22 @@ describe('UsersService', () => {
...
+        {
+          provide: getRepositoryToken(Friendship),
+          useValue: new MockRepository<Friendship>(
+            () => new Friendship(),
+            userNumber,
+          ),
+        },
+        {
+          provide: getRepositoryToken(Block),
+          useValue: new MockRepository<Block>(() => new Block(), userNumber),
```
Comment (fyusuf-a) [inline backend/src/users/users.service.spec.ts:46]:
```suggestion
          useValue: new MockRepository<Block>(() => new Block()),
```

File: backend/src/users/users.service.spec.ts [hunk 14]
```diff
@@ -60,10 +71,12 @@ describe('UsersService', () => {
...
-      const messages = await service.findAll();
-      expect(messages).toBeInstanceOf(PageDto);
-      if (messages.data.length !== 0)
-        expect(messages.data[0]).toBeInstanceOf(MockUserEntity);
+      jest
+        .spyOn(repository, 'findAndCount')
+        .mockReturnValue(Promise.resolve([[new User()], 1]));
+      const users = await service.findAll();
+      expect(users).toBeInstanceOf(PageDto);
+      if (users.data.length !== 0) expect(users.data[0]).toBeInstanceOf(User);
```
Comment (fyusuf-a) [inline backend/src/users/users.service.spec.ts:79]:
```suggestion
      const messages = await service.findAll();
      expect(messages).toBeInstanceOf(PageDto);
      if (messages.data.length !== 0)
        expect(messages.data[0]).toBeInstanceOf(MockUserEntity);
```
Works with the suggested change of `MockRepository`.

File: backend/src/users/users.service.ts [hunk 15]
```diff
@@ -1,38 +1,43 @@
...
+      this.usersRepository,
+      query,
+      orderOptions,
+      pageOptions,
+    );
   }
 
   findOne(id: number): Promise<User> {
-    return this.usersRepository.findOne(id);
+    return this.usersRepository.findOneByOrFail({ id: id });
```
Comment (fyusuf-a) [inline backend/src/users/users.service.ts:40]: Some services use `findOneBy`. I think it should be uniform across services. But it could be the object of a future issue.

File: backend/src/relationships/friendships/friendships.service.ts [hunk 16]
```diff
@@ -56,15 +57,23 @@ export class FriendshipsService {
     query?: QueryFriendshipDto,
     pageOptions: PageOptionsDto = new PageOptionsDto(),
   ): Promise<PageDto<ResponseFriendshipDto>> {
-    const response = await this.friendshipRepository.findAllPaginated(
-      query,
+    const orderOptions = { id: pageOptions.order };
+    const findOptionsWhere: FindOptionsWhere<Friendship> = {
+      source: query?.sourceId ? { id: +query.sourceId } : {},
+      target: query?.targetId ? { id: +query.targetId } : {},
+      status: query?.status ? query.status : undefined,
```
Comment (fyusuf-a) [inline backend/src/relationships/friendships/friendships.service.ts:64]:
```suggestion
      status: query?.status,
```
Those are strictly equivalent.

File: backend/src/users/users.service.ts (hunk 15 above)
Comment (tmorris42) [reply backend/src/users/users.service.ts:40]: I created issue #147 to discuss this. For now maybe it is better to change this to `findOneBy` because otherwise it is being updated for TypeORM **and** changing behavior. What do you think?

File: backend/src/common/paginate.ts (hunk 1 above)
Comment (tmorris42) [reply backend/src/common/paginate.ts]: Thank you, these suggestions improve the readability a lot.

I realized I could eliminate the second template parameter. See what you think, but I hope it makes it cleaner than what I had before.

File: dtos/memberships/query-membership.dto.ts (hunk 3 above)
Comment (tmorris42) [reply dtos/memberships/query-membership.dto.ts]: These suggestions made me realize that I could have avoided modifying the dtos.

File: backend/src/common/paginate.ts (hunk 1 above)
Comment (fyusuf-a) [reply backend/src/common/paginate.ts]: I think you are right, it is cleaner.
